Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

BuyerRatio.csv

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import statsmodels.api as sm
import scipy.stats as st
#from PIL import ImageGrab


%matplotlib inline
warnings.filterwarnings('ignore')

In [16]:
df=pd.read_csv('BuyerRatio.csv')
df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [17]:
dfNew=df.iloc[:,1:]
dfNew

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [18]:
arr=dfNew.values
arr

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [23]:
stat,p,dof,exp=st.chi2_contingency(dfNew)
print(stat,"\n", p,"\n", dof,"\n", exp)

1.595945538661058 
 0.6603094907091882 
 3 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [24]:
st.chi2_contingency(arr)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [31]:
observed=np.array([50,142,131,70,435,1523,1356,750])
expected=np.array( [42.76531299,146.81287862,131.11756787,72.30424052,442.23468701,1518.18712138,1355.88243213,747.69575948])

# Comparing Evidence with hypothesis

In [34]:
statistics,p_value=st.chisquare(observed,expected,ddof=3)
print("Statistics = ",statistics,"\n",'P_Value = ', p_value)

Statistics =  1.5959455390914483 
 P_Value =  0.8095206646905712


In [35]:
# Compare p_value with '
#  '(Significane Level)
# If p_value is 
#  '
#  ' we failed to reject Null Hypothesis because of lack of evidence
# If p_value is = '
#  ' we reject Null Hypothesis
# interpreting p-value

In [36]:
alpha = 0.05
print('Significnace=%.3f, p=%.3f' % (alpha, p_value))
if p_value <= alpha:
    print('We reject Null Hypothesis there is a significance difference between TAT of reports of the laboratories')
else:
    print('We fail to reject Null hypothesis')

Significnace=0.050, p=0.810
We fail to reject Null hypothesis
